#!/usr/bin/env bash
#It configures an Ubuntu server with these requirements: localhost resolves to 127.0.0.2, facebook.com resolves to 8#.8.8.8
echo 'localhost        127.0.0.2' >> /etc/hosts
echo 'facebook.com        8.8.8.8' >> /etc/hosts
